version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=mealvery
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  app:
    build:
      context: .
    ports:
      - "8007:8007"
    volumes:
      - "./app:/app"
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8007"
    depends_on:
      - db
    env_file:
      - ./.env.example
