version: "3"

services:
  # postgres database
  db:
    image: postgres
    environment:
      - POSTGRES_DB=mealvery
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  # python app
  app: &app
    build:
      context: .
    ports:
      - "8007:8007"
    volumes:
      - "./app:/app"
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8007"
    depends_on:
      - db
      - rabbitmq
      - celery_worker
    env_file:
      - ./.env
  # rabbit message queue
  rabbitmq:
    image: rabbitmq:3.8-alpine
  # celery worker service
  celery_worker:
    <<: *app
    command: celery -A mealvery worker --loglevel=info
    ports: []
    depends_on:
      - db
      - rabbitmq
