# Generated by Django 3.0.7 on 2020-06-08 00:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(verbose_name='date published')),
                ('dishes', models.ManyToManyField(to='dishes.Dish')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
