# Generated by Django 3.0.6 on 2020-05-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
