# Generated by Django 3.0.6 on 2020-05-30 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20200527_0605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-date']},
        ),
    ]
